title: xcatliu / 流浪小猫
description: A cat who writes code

social:
  - title: GitHub
    img: /assets/images/github.ico
    url: https://github.com/xcatliu
  - title: Gmail
    img: /assets/images/gmail.png
    url: mailto:xcatliu@gmail.com
  - title: V2EX
    img: /assets/images/v2ex.png
    url: https://www.v2ex.com/member/xcatliu?r=xcatliu
  - title: Twitter
    img: /assets/images/twitter.ico
    url: https://twitter.com/xcatliu
  - title: 知乎
    img: /assets/images/zhihu.ico
    url: https://www.zhihu.com/people/xcat-liu
  - title: 微博
    img: /assets/images/weibo.ico
    url: http://weibo.com/xcatliu

avatar: /assets/images/avatar.png
introduction: >
  Hi! My name is Xcat Liu.<br/>
  中文昵称是流浪小猫，也可以叫我小猫。<br/>
  Whenever you see this lovely cat, yeah that’s me!

working:
  title: Working Experience
  timeline:
    - date: Now
    - "Microsoft: Software Engineer II"
    - date: 2016-04
    - "Meituan: Senior Front-End Engineer"
    - date: 2015-04
    - "Meituan: Front-End Engineer"
    - date: 2013-06
    - "Meituan: Front-End Engineer Internship"
    - date: 2012-10

education:
  title: Education Background
  timeline:
    - date: 2013-06
    - "Bachelor of WuHan University: Computer Science and Technology"
    - date: 2009-09

google_analytics: UA-45256157-13
