title: xcatliu / 流浪小猫
description: A cat who writes code

avatar: /assets/avatar.png
introduction: >
  Hi! My name is Xcat Liu.<br/>
  中文昵称是流浪小猫，也可以叫我小猫。<br/>
  Whenever you see this lovely cat, yeah that’s me!

working:
  title: Working Experience
  timeline:
    - date: Now
    - Microsoft &nbsp;&nbsp; Software Engineer II
    - date: 2016-04
    - Meituan &nbsp;&nbsp; Senior Front-End Engineer
    - date: 2015-04
    - Meituan &nbsp;&nbsp; Front-End Engineer
    - date: 2013-06
    - Meituan &nbsp;&nbsp; Front-End Engineer Internship
    - date: 2012-10

education:
  title: Education Background
  timeline:
    - date: 2013-06
    - "Bachelor of WuHan University &nbsp;&nbsp; Major: Computer Science and Technology"
    - date: 2009-09