title: 不务正业的白白APPLE
description: A cat who loves code

social:
  - title: GitHub
    img: /assets/images/github.ico
    url: https://github.com/AACAES
  - title: V2EX
    img: /assets/images/v2ex.png
    url: https://www.v2ex.com/member/xcatliu?r=xcatliu
  - title: Blog
    img: /assets/images/avatar.png
    url: https://www.applecaes.xyz
  - title: Twitter
    img: /assets/images/twitter.ico
    url: https://twitter.com/AACAES
  - title: Gmail
    img: /assets/images/gmail.png
    url: mailto:assassionsiege@gmail.com

avatar: /assets/images/avatar.png
introduction: >
  Hi! My nickname is Apple.<br/>
  叫Apple不是装逼，我中文名谐音我有啥办法。。。略略略~~~<br/>
  中文昵称是太多了。。。。<br/>
  Whenever you see this lovely cat, yeah that’s me!

projects:
  title: Open Source Projects
  github:
    - xcatliu/mobi.css
    - xcatliu/typescript-tutorial
    - xcatliu/react-ie8
    - xcatliu/jekyllcn
    - xcatliu/leetcode
  content: >
    <p>Other projects that I have contributed can be found in <a href="https://github.com/AACAES">github.com/AACAES</a>.</p>
    <p>If you love my projects, please <a href="https://github.com/AACAES/buy-me-a-coffee">buy me a coffee</a> to support me.</p>
    <p>没错，上面的项目都不是我的，我用的模版里的哈哈哈~~~</p>

working:
  title: Working Experience
  timeline:
    - date: Now
    - "KPMG: Software Engineer II"
    - date: 2016-04
    - "Meituan: Senior Front-End Engineer"
    - date: 2015-04
    - "Meituan: Front-End Engineer"
    - date: 2013-06
    - "Meituan: Front-End Engineer Internship"
    - date: 2012-10

education:
  title: Education Background
  timeline:
    - date: Now
    - "NCEPU: thermal engineering /postgraduate"
    - date: 2015-09
    - "NCEPU: Architectural Environment & Equipment Engineering /undergraduate"
    - date: 2011-09

aboutme:
  title: 关于我
  content: >
    <p>研究生二年级。。研三了。。。在读，热能工程专业，对，你没看错，我不是计算机一类专业的人，是烧锅炉的。。。</p>
    <p>研究方向是压缩空气储能（CAES）和风力机的气动性能，对，你还没看错，这两方向确实不沾边。。。</p>
    <p>我一直相信科技让生活更美好，也一直喜欢计算机，虽然水平比较差，但是一直在变好。</p>
    
aboutthisblog:
  title: 关于这个博客
  content: >
    <p>我最初搞这个blog也算是无心插柳，不过现在我打算用来记录自己捣鼓树莓派的经历。</p>
    <p>因为在计算机方向，我算是泥腿子出身，在按照网上教程折腾的时候，发现许多教程要么太粗略，要么有各种错误，所以在这里我详细写一下我的操作步骤和我遇到的问题，还有一些心得，让零基础的大伙也能成功搞出结果。</p>
    


google_analytics: UA-45256157-13
